adaptive_noise_scale = 0
ae = "D:/Finetune/Finetune/Models/ae.safetensors"
blocks_to_swap = 0
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_dropout_every_n_epochs = 0
caption_dropout_rate = 0
caption_extension = ".txt"
clip_l = "D:/Finetune/Finetune/Models/clip_l.safetensors"
clip_skip = 1
discrete_flow_shift = 3
double_blocks_to_swap = 0
dynamo_backend = "no"
enable_bucket = true
epoch = 6
gradient_accumulation_steps = 1
gradient_checkpointing = true  # 启用梯度检查点以节省显存
guidance_scale = 3.5
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
keep_tokens = 0
learning_rate = 2e-5  # 调整为稍高但仍安全的学习率
learning_rate_te = 2e-5  # 与主学习率保持一致
logging_dir = ".\\Models_Output"
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 50  # 添加少量预热步骤以提高稳定性
maxhrt_reso = 2048
max_data_loader_n_workers = 2  # 增加到 2，提升数据加载效率
max_timestep = 1000
max_token_length = 75
max_train_steps = 1600  # 保持不变
min_bucket_reso = 256
mixed_precision = "bf16"  # 改为 bf16，避免 FP16 的梯度问题
model_prediction_type = "sigma_scaled"
multires_noise_discount = 0.3
multires_noise_iterations = 6  # 添加多分辨率噪声，提升稳定性
noise_offset = 0.05  # 添加少量噪声偏移，改善训练质量
noise_offset_type = "Original"
optimizer_type = "AdamW"
output_dir = ".\\Models_Output"
output_name = "last"
persistent_data_loader_workers = true  # 启用持久化工作线程
pretrained_model_name_or_path = "D:/Finetune/Finetune/Models/flux_dev.safetensors"
prior_loss_weight = 1
resolution = "512,512"
sample_prompts = ".\\Models_Output\\sample/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 2
save_model_as = "safetensors"
save_precision = "bf16"  # 与 mixed_precision 保持一致
single_blocks_to_swap = 0
t5xxl = "D:/Finetune/Finetune/Models/t5xxl_fp8_e4m3fn.safetensors"
t5xxl_max_token_length = 512
timestep_sampling = "sigma"
train_batch_size = 1
train_blocks = "all"
train_data_dir = ".\\Datasets\\Custom_Images_Keai"
wandb_run_name = "last"
xformers = true